common.language.push([
	{ lanKey: 'onlineAna', msg: "Online Analysis" },
	{ lanKey: 'collectMail', msg: "Collect and share the mail or WeChat" },
	{ lanKey: 'constrast', msg: "Graphical Data comparison" },
	{ lanKey: 'exportFile', msg: "Export File(.xls)" },
	{ lanKey: 'moreActions', msg: "More Actions" },
	{ lanKey: 'shareControl', msg: "Share Control" },
	{ lanKey: 'showSqlCode', msg: "Show Sql Code" },
	{ lanKey: 'sqlImplement', msg: "Sql Implement" },
	{ lanKey: 'refreshControl', msg: "Refresh Control" },
	{ lanKey: 'dataComparison', msg: "Data Compare" },
	{ lanKey: 'addFavorites', msg: "Add To Favorites" },
	{ lanKey: 'exportXls', msg: "Export Xls" },
	{ lanKey: 'exportCsv', msg: "Export Csv" },
    { lanKey: 'exportXlsSeen', msg: "Export Xls_seen" },


	{ lanKey: 'collectChart', lanId: '10', msg: "ChartTable" },
    { lanKey: 'myCollectChart', lanId: '11', msg: "My ChartTable" },
    { lanKey: 'selCollectChart', lanId: '12', msg: "Folder" },
    { lanKey: 'updateCollect', msg: "Modify" },
    { lanKey: 'insertCollect', msg: "New" },
    { lanKey: 'insertCollectChart', lanId: '13', msg: "insertFolder" },
    { lanKey: 'sure', lanId: '14', msg: "sure" },
    { lanKey: 'setShareTimingMail', lanId: '15', msg: "Set Share Timing(Mail)" },
    { lanKey: 'close', lanId: '16', msg: "close" },
    { lanKey: 'back', msg: "back" },
    { lanKey: 'collectionsListnull1', lanId: '17', msg: "Click on the icon at the top right" },
    { lanKey: 'collectionsListnull2', lanId: '18', msg: "began to collect." },
    { lanKey: 'collectSuccess', msg: "Collect Success!" },
    { lanKey: 'unNamed', msg: "unNamed" },
    { lanKey: 'updateName', msg: "reName" },
    { lanKey: 'nullInputCollect', msg: "Favorite Name not Filled!" },

    { lanKey: 'personInCharge', msg: "Person In Charge:" },
    { lanKey: 'prodcutionPersonInCharge', msg: "Production Person In Charge" },
    { lanKey: 'difficultToFind', msg: "Difficult To Find:" },
    { lanKey: 'indexDescription', msg: "Index Description" },
    { lanKey: 'remove', msg: "Remove" },
    { lanKey: 'preview', msg: "Preview" },
    { lanKey: 'chartPreview', msg: "ChartPreview-" },
    { lanKey: 'deleted', msg: "Deleted" },
    { lanKey: 'chart', msg: "Chart" },
    { lanKey: 'recovery', msg: "Recovery" },
    { lanKey: 'refresh', msg: "refresh" },
    { lanKey: 'refreshPage', msg: "Refresh Page" },
    { lanKey: 'print', msg: "print" },
    { lanKey: 'printPage', msg: "Print Page" },

    { lanKey: 'width', msg: "Width" },
    { lanKey: 'colon', msg: ":" },
    { lanKey: 'height', msg: "Height" },
    { lanKey: 'showQueryToolbar', msg: "Show Query Toolbar" },
    { lanKey: 'yes', msg: "Yes" },
    { lanKey: 'not', msg: "No" },
    { lanKey: 'shareCode', msg: "Share Code" },
    { lanKey: 'manuallyCopy', msg: "Copy" },
    { lanKey: 'pageLink', msg: "Page Link" },
    { lanKey: 'open', msg: "Open" },

    { lanKey: 'advancedEmbed', msg: "Advanced Embed" },
    { lanKey: 'advancedEmbedMsg', msg: "will help you to graph or chart embedded into your page,convenient you override the click event or style." },
    { lanKey: 'introduce', msg: "Introduce" },
    { lanKey: 'toYourPage', msg: "to Your Page." },
    { lanKey: 'inTheIntroductionOf', msg: "in the introduction of" },
    { lanKey: 'before', msg: "before" },
    { lanKey: 'comma', msg: "," },
    { lanKey: 'pleaseConfirm', msg: "please confirm" },
    { lanKey: 'haveBeenIntoPage', msg: "have been introduced into your page." },
    { lanKey: 'firstSteps', msg: "Step 1" },
    { lanKey: 'secondSteps', msg: "Step 2" },
    { lanKey: 'configure', msg: "Configure" },
    { lanKey: 'setCrossDomain', msg: "CrossDomain" },
    { lanKey: 'configurationCode', msg: "ConfigCode" },
    { lanKey: 'secondStepsMsg', msg: "CrossDomain into the domain name width the epr agreement,such as:\"oa.com\",then the ConfigCode in your pages,so that the“externalOptions.js”can be found on your page references epr iframe carried out a series of the allocation of the." },
    { lanKey: 'eventBind', msg: "Event Bind" },
    { lanKey: 'eventBindTitle', msg: "Use the control \"Event Bind\" code." },
    { lanKey: 'eventBindMsg', msg: "the binding event code will be passed in the \"clickModal\" object,the object that contains the current click point data(rows of data and some of the data on epr page,example:app information、page object、control object),for your convenience." },
    { lanKey: 'graphicStyle', msg: "Graph Style" },
    { lanKey: 'graphicStyleTitle', msg: "HighCharts style control graph control." },
    { lanKey: 'graphicStyleMsg', msg: "when using the callback,will the incoming HighCharts chart configuration file,you can modify the configuration file according to the demand of,and then return it to system,the system will render you modify the style." },

    { lanKey: 'copy', msg: "Copy" },
    { lanKey: 'clickCopy', msg: "Click Copy" },
    { lanKey: 'copySuccess', msg: "Copy Success" },
    { lanKey: 'copyerr', msg: "Because chrome and firefox browser screen paste board,so please manually copy!" },

    { lanKey: 'share', msg: "Share" },

    { lanKey: 'dataErr', msg: "Data Error!" },
    { lanKey: 'dataNull', msg: "Data Null!" },
    { lanKey: 'contrastTerms', msg: "Contrast" },
    { lanKey: 'clickRename', msg: "Click Rename" },
    { lanKey: 'removeConditions', msg: "Remove Conditions" },
    { lanKey: 'addConditions', msg: "AddCondition" },
    { lanKey: 'startContrast', msg: "Start Contrast" },
    { lanKey: 'confluence', msg: "Confluence" },

    { lanKey: 'viewSqlCode', msg: "View Sql Code" },
    { lanKey: 'runTime', msg: "Run Time" },
    { lanKey: 'returnResult', msg: "Result" },
    { lanKey: 'errorSp', msg: "Error" },
    { lanKey: 'errorMessage', msg: "Error Message" },
    { lanKey: 'slipRows', msg: "rows" },
    { lanKey: 'sDate', msg: "s" },

    { lanKey: 'search', msg: "Search" },
    { lanKey: 'saveParam', msg: "save" },

    { lanKey: 'prevYearDate', msg: "Prev" },
    { lanKey: 'nextYearDate', msg: "Next" },
    { lanKey: 'firstHalfYearDate', msg: "firstHalf" },
    { lanKey: 'secondHalfYearDate', msg: "secondHalf" },
    { lanKey: 'yearDate', msg: " " },
    { lanKey: 'monthDate', msg: " " },
    { lanKey: 'toDate', msg: "to" },
    { lanKey: 'chckBoxListPlaceHolder', msg: "Please click here.." },
    { lanKey: 'searchRe', msg: "Search" },
    { lanKey: 'selectAllCom', msg: "[All]" },
    { lanKey: 'inverseCom', msg: "[Inverse]" },
    { lanKey: 'notResultData', msg: "no data!" },

    { lanKey: 'lockMsg', msg: "click on the lock,the other page of the query conditions and current conditions remain the same" },
    { lanKey: 'unLockMsg', msg: "click to cancel locking" },

    { lanKey: 'createControlErr', msg: "Create Control Error:" },
    { lanKey: 'getToolbarControl', msg: "Get Toolbar Control:" },
    { lanKey: 'failed', msg: "Failed" },

    { lanKey: 'dataTabelsNull', msg: "In the condition of no data,Please try other conditions!" },
    { lanKey: 'isDataHasError', msg: "Sorry,Data error~~" },
    { lanKey: 'pagingDataError', msg: "The SQL statement is due to mistakes in the paging process~~</br>Error Message(From the database):</br>" },
    { lanKey: 'conditionsCompareMsg', msg: "Please select a condition comparison" },
    { lanKey: 'minutes', msg: " Minutes" },
    { lanKey: 'refreshControlTime', msg: " Seconds later,Refresh Control." },
    { lanKey: 'minutesToRefresh', msg: " Minutes to refresh time!" },
    
    { lanKey: 'desOrder', msg: "Desending" },
    { lanKey: 'ascOrder', msg: "Ascending" },
    { lanKey: 'frozen', msg: "FrozenColumn" },
    { lanKey: 'showSum', msg: "Show Sum" },
    { lanKey: 'showMean', msg: "Show Avg" },
    { lanKey: 'showMax', msg: "Show Max" },
    { lanKey: 'showMin', msg: "Show Min" },
    { lanKey: 'showCount', msg: "Show Count" },
    { lanKey: 'copyColumn', msg: "CopyColumn" },
    { lanKey: 'showWeek', msg: "Show Week" },
    { lanKey: 'sum', msg: "Sum" },
    { lanKey: 'max', msg: "Max" },
    { lanKey: 'min', msg: "Min" },
    { lanKey: 'count', msg: "Count" },
    { lanKey: 'svg', msg: "Svg" },
    { lanKey: 'noData', msg: "No Data!" },
    { lanKey: 'expandClose', msg: "Expand/Close" },
    { lanKey: 'dragCellSize', msg: "Drag The Cell Size" },
    { lanKey: 'consumingQueries', msg: "Consuming Queries" },
    { lanKey: 'consumingQueriesMsg', msg: ", The amount of data the query may have more than 500,data show folding,To see the full data,click the top right of the table Export." },
    { lanKey: 'clickOpen', msg: "Click Open" },
    { lanKey: 'columnMenu', msg: "Column Menu" },
    { lanKey: 'cutover', msg: "Cutover" },
    { lanKey: 'chartTableCut', msg: "Chart/Table" },
    { lanKey: 'range', msg: "Range" },
    { lanKey: 'chartDataErrMsg', msg: "Chart data format error,chart may be unable to generate,Please contact the administrator!" },
    { lanKey: 'formatDateBigData', msg: "yyyy-MM-dd" },
    { lanKey: 'top', msg: "Top" },
    { lanKey: 'current', msg: "Current" },
    { lanKey: 'maxHeighest', msg: "Max" },
    { lanKey: 'average', msg: "Average" },
    { lanKey: 'today', msg: "Today" },
    { lanKey: 'yesterday', msg: "Yesterday" },
    { lanKey: 'preWeek', msg: "prev Week" },
    { lanKey: 'viewDetails', msg: "View Details" },
    { lanKey: 'maxValue', msg: "Max" },
    { lanKey: 'minValue', msg: "Min" },
    { lanKey: 'currentValue', msg: "Current" },
    { lanKey: 'null', msg: "Null" },
    { lanKey: 'noPagingData', msg: "No Paging Data！" },
    { lanKey: 'detailsMsg', msg: "Details" },
    { lanKey: 'getDataError', msg: "Get Data Error" },
    { lanKey: 'perspective', msg: "Perspective" },
    { lanKey: 'loading.', msg: "Loading.." },

    { lanKey: 'sysDefault', lanId: "sysDefault", msg: "Default" },
    { lanKey: 'blue', lanId: "blue", msg: "Blue" },
    { lanKey: 'app_sel_body', lanId: "app_sel_body", msg: "Search by name or ID" },

    { lanKey: 'noneMenuItem',msg: "None Name Menu Item" },
    { lanKey: 'noneAppName', msg: "None AppName" },
    { lanKey: 'noneTitle', msg: "None Title" }
]);