common.language.push([
	{ lanKey: 'onlineAna', msg: "在线分析" },
	{ lanKey: 'collectMail', msg: "收藏并分享到邮件或微信" },
	{ lanKey: 'constrast', msg: "图形数据对比" },
	{ lanKey: 'exportFile', msg: "导出文件(.xls)" },
	{ lanKey: 'moreActions', msg: "更多操作" },
	{ lanKey: 'shareControl', msg: "分享控件" },
	{ lanKey: 'showSqlCode', msg: "显示sql代码" },
	{ lanKey: 'sqlImplement', msg: "sql执行情况" },
	{ lanKey: 'refreshControl', msg: "刷新控件" },
	{ lanKey: 'dataComparison', msg: "数据对比" },
	{ lanKey: 'addFavorites', msg: "加入收藏" },
	{ lanKey: 'exportXls', msg: "导出xls" },
	{ lanKey: 'exportCsv', msg: "导出csv" },
    { lanKey: 'exportXlsSeen', msg: "导出所见数据(.xls)" },

	{ lanKey: 'collectChart', lanId: '10', msg: "图表收藏夹" },
    { lanKey: 'myCollectChart', lanId: '11', msg: "我的收藏夹" },
    { lanKey: 'selCollectChart', lanId: '12', msg: "选择收藏夹" },
    { lanKey: 'updateCollect', msg: "修改" },
    { lanKey: 'insertCollect', msg: "新增" },
    { lanKey: 'insertCollectChart', lanId: '13', msg: "新增收藏夹" },
    { lanKey: 'sure', lanId: '14', msg: "确定" },
    { lanKey: 'setShareTimingMail', lanId: '15', msg: "设置定时分享（邮件）" },
    { lanKey: 'close', lanId: '16', msg: "关闭" },
    { lanKey: 'back',  msg: "返回" },
    { lanKey: 'collectionsListnull1', lanId: '17', msg: "当前收藏夹为空，可点击图表右上方" },
    { lanKey: 'collectionsListnull2', lanId: '18', msg: "开始收藏。" },
    { lanKey: 'collectSuccess', msg: "收藏已成功添加!" },
    { lanKey: 'unNamed', msg: "我的收藏" },
    { lanKey: 'updateName', msg: "修改名称" },
    { lanKey: 'nullInputCollect', msg: "未填写收藏夹名称！" },

    { lanKey: 'personInCharge', msg: "负责人：" },
    { lanKey: 'prodcutionPersonInCharge', msg: "业务负责人" },
    { lanKey: 'difficultToFind', msg: "有困难找：" },
    { lanKey: 'indexDescription', msg: "指标说明" },
    { lanKey: 'remove', msg: "移除" },
    { lanKey: 'preview', msg: "预览" },
    { lanKey: 'chartPreview', msg: "图表预览-" }, 
    { lanKey: 'deleted', msg: "已删除" },
    { lanKey: 'chart', msg: "图表" },
    { lanKey: 'recovery', msg: "恢复" },
    { lanKey: 'refresh', msg: "刷新" },
    { lanKey: 'refreshPage', msg: "页面刷新" },
    { lanKey: 'print', msg: "打印" },
    { lanKey: 'printPage', msg: "页面打印模式" },

    { lanKey: 'width', msg: "宽度" },
    { lanKey: 'colon', msg: "：" },
    { lanKey: 'height', msg: "高度" },
    { lanKey: 'showQueryToolbar', msg: "显示查询工具栏" },
    { lanKey: 'yes', msg: "是" },
    { lanKey: 'not', msg: "否" },
    { lanKey: 'shareCode', msg: "分享代码" },
    { lanKey: 'manuallyCopy', msg: "手动复制" },
    { lanKey: 'pageLink', msg: "页面链接" },
    { lanKey: 'open', msg: "打开" },

    { lanKey: 'advancedEmbed', msg: "高级嵌入" },
    { lanKey: 'advancedEmbedMsg', msg: "将帮助您将epr图形或图表嵌入到您的页面中,方便您重写单击事件,或样式。" },
    { lanKey: 'introduce', msg: "引入" },
    { lanKey: 'toYourPage', msg: "到您的页面。" },
    { lanKey: 'inTheIntroductionOf', msg: "在引入" },
    { lanKey: 'before', msg: "之前" },
    { lanKey: 'comma', msg: "，" },
    { lanKey: 'pleaseConfirm', msg: "请确认" },
    { lanKey: 'haveBeenIntoPage', msg: "已经被引入进您的页面中。" },
    { lanKey: 'firstSteps', msg: "第一步" },
    { lanKey: 'secondSteps', msg: "第二步" },
    { lanKey: 'configure', msg: "配置" },
    { lanKey: 'setCrossDomain', msg: "设置跨域" },
    { lanKey: 'configurationCode', msg: "配置代码" },
    { lanKey: 'secondStepsMsg', msg: "跨域设置填入与epr一致的主域名，如:“oa.com”，再将配置代码放入您的页面之中，以便“externalOptions.js”可以找到您页面上引用了epr的iframe对其进行一系列的配置。" },
    { lanKey: 'eventBind', msg: "事件绑定" },
    { lanKey: 'eventBindTitle', msg: "使用该控件的“事件绑定”代码。" },
    { lanKey: 'eventBindMsg', msg: "事件绑定代码将传入“clickModal”对象，该对象包含当前所单击的点上的数据、行的数据以及一些epr页面上的数据例如app信息、页面对象、控件对象以方便您使用。" },
    { lanKey: 'graphicStyle', msg: "图形样式" },
    { lanKey: 'graphicStyleTitle', msg: "HighCharts图形控件的样式控制。" },
    { lanKey: 'graphicStyleMsg', msg: "使用该回调时，将传入图形控件在即将渲染时所使用的HighCharts图表配置文件，您可以根据需求修改配置文件然后将它再return给系统，系统将渲染您修改的样式。" },

    { lanKey: 'copy', msg: "复制" },
    { lanKey: 'clickCopy', msg: "点击复制" },
    { lanKey: 'copySuccess', msg: "复制成功!" },
    { lanKey: 'copyerr', msg: "因chrome,firefox等浏览器屏蔽黏贴板，故请手动复制一下！" },

    { lanKey: 'share', msg: "分享" },

    { lanKey: 'dataErr', msg: "数据出错!" },
    { lanKey: 'dataNull', msg: "数据为空!" },
    { lanKey: 'contrastTerms', msg: "对比条件" },
    { lanKey: 'clickRename', msg: "点击重命名" },
    { lanKey: 'removeConditions', msg: "删除条件" },
    { lanKey: 'addConditions', msg: "增加条件" },
    { lanKey: 'startContrast', msg: "开始对比" },
    { lanKey: 'confluence', msg: "总汇" },

    { lanKey: 'viewSqlCode', msg: "查看SQL语句" },
    { lanKey: 'runTime', msg: "执行时间" },
    { lanKey: 'returnResult', msg: "返回结果" },
    { lanKey: 'errorSp', msg: "出错" },
    { lanKey: 'errorMessage', msg: "出错信息" },
    { lanKey: 'slipRows', msg: "条" },
    { lanKey: 'sDate', msg: "秒" },

    { lanKey: 'search', msg: "查询" },
    { lanKey: 'saveParam', msg: "保存参数" },

    { lanKey: 'prevYearDate', msg: "上一年" },
    { lanKey: 'nextYearDate', msg: "下一年" },
    { lanKey: 'firstHalfYearDate', msg: "上半年" },
    { lanKey: 'secondHalfYearDate', msg: "下半年" },
    { lanKey: 'yearDate', msg: "年" },
    { lanKey: 'monthDate', msg: "月" },
    { lanKey: 'toDate', msg: "至" },
    { lanKey: 'chckBoxListPlaceHolder', msg: "请点击此处选择.." },
    { lanKey: 'searchRe', msg: "搜索" },
    { lanKey: 'selectAllCom', msg: "【全选】" },
    { lanKey: 'inverseCom', msg: "【反选】" },
    { lanKey: 'notResultData', msg: "没有取到数据哦！" },

    { lanKey: 'lockMsg', msg: "点击锁定后，其他页面的查询条件会和当前条件保持一致" },
    { lanKey: 'unLockMsg', msg: "点击取消锁定条件" },
    
    { lanKey: 'createControlErr', msg: "创建控件失败:" },
    { lanKey: 'getToolbarControl', msg: "获取工具栏控件:" },
    { lanKey: 'failed', msg: "失败" },

    { lanKey: 'dataTabelsNull', msg: "本条件暂无数据，请尝试其他条件！" },
    { lanKey: 'isDataHasError', msg: "不好意思，数据出错啦！~~" },
    { lanKey: 'pagingDataError', msg: "分页过程中出现了因SQL语句导致的错误！~~</br>错误信息如下（此错误由数据库抛出）：</br>" },
    { lanKey: 'conditionsCompareMsg', msg: "请选择一个条件以进行对比" },
    { lanKey: 'minutes', msg: "分钟" },
    { lanKey: 'refreshControlTime', msg: "秒后刷新控件." },
    { lanKey: 'minutesToRefresh', msg: "分钟刷新一次!" },

    { lanKey: 'desOrder', msg: "降序排序" },
    { lanKey: 'ascOrder', msg: "升序排序" },
    { lanKey: 'frozen', msg: "冻结本列" },
    { lanKey: 'showSum', msg: "显示合计" },
    { lanKey: 'showMean', msg: "显示均值" },
    { lanKey: 'showMax', msg: "显示最大" },
    { lanKey: 'showMin', msg: "显示最小" },
    { lanKey: 'showCount', msg: "显示数量" },
    { lanKey: 'copyColumn', msg: "拷贝本列" },
    { lanKey: 'showWeek', msg: "显示星期" },
    { lanKey: 'sum', msg: "合计" },
    { lanKey: 'max', msg: "最大" },
    { lanKey: 'min', msg: "最小" },
    { lanKey: 'count', msg: "数量" },
    { lanKey: 'svg', msg: "均值" },
    { lanKey: 'noData', msg: "暂无数据哦，亲！" },
    { lanKey: 'expandClose', msg: "展开/关闭" },
    { lanKey: 'dragCellSize', msg: "拖动单元大小" },
    { lanKey: 'consumingQueries', msg: "查询耗时" },
    { lanKey: 'consumingQueriesMsg', msg: ",注意，此次查询数据量可能已超过五百条，数据将折页显示，若要查看完整数据，请点击表格右上方导出。" },
    { lanKey: 'clickOpen', msg: "点击打开" },
    { lanKey: 'columnMenu', msg: "列功能菜单" },
    { lanKey: 'cutover', msg: "切换" },
    { lanKey: 'chartTableCut', msg: "图/表" },
    { lanKey: 'range', msg: "范围" },
    { lanKey: 'chartDataErrMsg', msg: "图表数据格式错误,图形可能无法正确生成，请联系管理员检查！" },
    { lanKey: 'formatDateBigData', msg: "yyyy年MM月dd" },
    { lanKey: 'top', msg: "顶部" },
    { lanKey: 'current', msg: "当前" },
    { lanKey: 'maxHeighest', msg: "最高" },
    { lanKey: 'average', msg: "平均" },
    { lanKey: 'today', msg: "今天" },
    { lanKey: 'yesterday', msg: "昨天" },
    { lanKey: 'preWeek', msg: "上周" },
    { lanKey: 'viewDetails', msg: "查看明细" },
    { lanKey: 'maxValue', msg: "最大值" },
    { lanKey: 'minValue', msg: "最小值" },
    { lanKey: 'currentValue', msg: "当前值" },
    { lanKey: 'null', msg: "空" },
    { lanKey: 'noPagingData', msg: "暂无分页数据！" },
    { lanKey: 'detailsMsg', msg: "详细信息" },
    { lanKey: 'getDataError', msg: "获取数据出错" },
    { lanKey: 'perspective', msg: "透视图" },
    { lanKey: 'loading.', msg: "正在载入.." },

    { lanKey: 'sysDefault', lanId: "sysDefault", msg: "系统默认" },
    { lanKey: 'blue', lanId: "blue", msg: "蓝色" },
    { lanKey: 'app_sel_body', lanId: "app_sel_body", msg: "按名称或ID模糊查询" },

    { lanKey: 'noneMenuItem', msg: "未命名" },
    { lanKey: 'noneAppName', msg: "未命名" },
    { lanKey: 'noneTitle', msg: "无标题" }
]);